[general]
startOnBoot=false
showInTray=false
minimizeToTray=false
closeToTray=false

[database]
databasePath=""
backupEnabled=false
backupPath=""
deleteBackupsAfter=0

[stopwatch]
minimizeStopwatchWindow=false
hideWindowTimer=1
notificationTimer=15
pausedTaskReminder=1
startStopwatchOnLaunch=false
startStopwatchOnResume=false

[task_item]
timeRounding=false
timeToRoundTo=5

[persistence]
dimensions="600,500"

[export]
delimiter=","
exportPath=""
